version: '2'

services:
  postgres:
    restart: unless-stopped
    image: postgres:9.6.4-alpine
    env_file:
      - ../.env

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.7.8
    env_file:
      - ../.env

  django:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: Dockerfile-dev
    ports:
      - "80:4000"
    volumes:
      - ../:/app/
    depends_on:
      - postgres
    env_file:
      - ../.env
